version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: new-estate-app
    container_name: new-real-estate-container 
    command: php artisan serve --host=0.0.0.0 --port=9090
    volumes:
      - .:/var/www/html
    ports:
      - "9090:9090"
    depends_on:
      - db
 

  db:
    image: mysql:latest
    container_name: new-estate-mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: realestate
      MYSQL_PASSWORD: password
    ports:
      - "3303:3303"
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
